version: '3.9'

services:
  web:
    build:
      context: .
    image: 'store-web'
    container_name: 'store-web'
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
  db:
    image: 'postgres:14-alpine'
    container_name: 'store-db'
    env_file: ./.env
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

